---
- name: Install Apache
  hosts: servers
  become: true
  gather_facts: true

  tasks:
    - name: Create facts Redhat
      ansible.builtin.set_fact:
        apache_package: "httpd"
      when: ansible_facts['distribution'] == "RedHat"

    - name: Create facts Ubuntu
      ansible.builtin.set_fact:
        apache_package: "apache2"
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Install Apache
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - php
          # - mariadb
        state: present
